### ISSUE TITLE
Error while running frontend code (Missing api/sources file)

### ISSUE THREAD

**Issue by rawzone** [martincollignon/landbrugsdata#43]
When trying to run the frontend via `npm start` or `npm run start`.

It throws the following error as it seems to miss the `api/sources` file:

```sh
Compiled successfully!

You can now view agricultural-data-frontend in the browser.

  Local:            http://localhost:3000
  On Your Network:  http://192.168.1.10:3000

Note that the development build is not optimized.
To create a production build, use npm run build.

webpack compiled successfully
Files successfully emitted, waiting for typecheck results...
Issues checking in progress...
ERROR in src/hooks/useMapData.ts:2:47
TS2307: Cannot find module '../api/sources' or its corresponding type declarations.
    1 | import { useState, useEffect } from 'react';
  > 2 | import { fetchSources, fetchSourceData } from '../api/sources';
      |                                               ^^^^^^^^^^^^^^^^
    3 | import { MapSource } from '../types/sources';
    4 |
    5 | const SOURCE_COLORS = {
```

The code comes from here:
https://github.com/martincollignon/landbrugsdata/blob/dcabd5dda00c5ca0cb0c6b5126331b6397dde3b6/frontend/src/hooks/useMapData.ts#L2

**Comment by rawzone** [comment]
Another little thing, while trying to get the frontend code to compile I had to manually add a few packages via npm:

```sh
@babel/plugin-proposal-class-properties
@babel/plugin-proposal-private-property-in-object
```

**Comment by martincollignon** [comment]
I haven't looked at frontend yet, so it is pure garbage. the little thinking i've done so far would be to use react and then protomaps, maplibre and d3 for the visualisation!

**Comment by rawzone** [comment]
OK that makes sense then will keep an eye on the progress.
Guess Ill wait a bit to toy around with it.
